parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
extends:
  - "plugin:@typescript-eslint/recommended"
env:
  node: true
rules:
  "@typescript-eslint/no-unused-vars": warn
