name: Release Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    steps:
      - name: Downloading repo
        uses: actions/checkout@v4
      - name: Setting up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Installing dependencies
        run: npm ci
      - name: Bumping version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version --no-git-tag-version ${{ github.ref_name }}
          git add package.json package-lock.json
          git commit -m "${{ github.ref_name }}"
      - name: Publishing package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
