name: PR
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  code_analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Downloading repo
        uses: actions/checkout@v4
      - name: Setting up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Installing dependencies
        run: npm ci
      - name: Running linter
        run: npm run lint
      - name: Running unit tests
        run: npm run test
        env:
          AWS_ACCESS_KEY_ID: 'dummy_key_id'
          AWS_SECRET_ACCESS_KEY: 'dummy_secret_key'
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Verify plugin can be built
        run: npm run build
